apiVersion: v1
kind: Service
metadata:
  name: fastapi
spec:
  selector:
    app: fastapi
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  labels:
    app: fastapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
        generation: '12'
    spec:
      containers:
      - name: fastapi
        image: ghcr.io/tuna2134/fastapi-and-docker
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
