name: Push to github container register

on:
  push:
    branches: main
    
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: |
          docker build ghcr.io/${{ GITHUB_REPOSITORY }} .
      - name: Push image
        run: |
          docker push ghcr.io/${{ GITHUB_REPOSITORY }}
