name: Push to github container register

on:
  push:
    branches: main

permissions:
  packages: "write|read"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: |
          docker build -t ghcr.io/$GITHUB_REPOSITORY .
      - name: Push image
        run: |
          docker push ghcr.io/$GITHUB_REPOSITORY
